SRC/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SRC/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1st year</fullName>
                </value>
                <value>
                    <fullName>2nd year</fullName>
                </value>
                <value>
                    <fullName>3rd year</fullName>
                </value>
                <value>
                    <fullName>4th year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Roll_Number__c</fullName>
        <label>Roll Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stream__c</fullName>
        <label>Stream</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Science</fullName>
                </value>
                <value>
                    <fullName>Commerce</fullName>
                </value>
                <value>
                    <fullName>Arts</fullName>
                </value>
                <value>
                    <fullName>Computer</fullName>
                </value>
                <value>
                    <fullName>Weapon Science</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Geology</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SRC/classes/StudentRecord.cls
public with sharing class StudentRecord {

        public static void yogaClass() {
        
            //Student_c student = new Student_c();
            // Hierarchical Collection example using Map and List
            Map<String, Map<String, List<Student__c>>> yogaClassMap = new Map<String, Map<String, List<Student__c>>>();
    
            // 2nd Year List of Student
            List<Student__c> firststYearListComputer = new List<Student__c>();
            firststYearListComputer = [SELECT ID, Name, Roll_Number__c, Class__c, Stream__c 
            from Student__c 
            where Class__c = '2nd year' and Stream__c = 'Science'];
            Map<String, List<Student__c>> mapOfStudentwithStream1stYear = new Map<String, List<Student__c>>();
            mapOfStudentwithStream1stYear.put('Computer Science', firststYearListComputer);
    
            // 2nd Year List of Student
            List<Student__c> firststYearListComputer_1 = new List<Student__c>();
            firststYearListComputer_1 = [SELECT ID , Name, Roll_Number__c, Class__c, Stream__c 
            from Student__c 
            where Class__c = '2nd year' and Stream__c = 'Science'];
            mapOfStudentwithStream1stYear.put('Electronic',firststYearListComputer_1);
    
            // 2nd Year List of Student
            List<Student__c> secondYearListElectronic = new List<Student__c>();
            secondYearListElectronic = [SELECT ID, Name, Roll_Number__c, Class__c, Stream__c 
            from Student__c 
            where Class__c = '2nd year' and Stream__c = 'Science'];
            Map<String, List<Student__c>> mapOfStudentwithStream2ndYear = new Map<String, List<Student__c>>();
            mapOfStudentwithStream2ndYear.put('Electronic', secondYearListElectronic);
    
            yogaClassMap.put('1stYear', mapOfStudentwithStream1stYear);
            yogaClassMap.put('2ndYear', mapOfStudentwithStream2ndYear);
            System.debug(yogaClassMap);
        }
    }