SRC/Major Assignment/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <displayFormat>AccNo-{00000}</displayFormat>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Available_Balance__c</fullName>
        <label>Available Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SRC/Major Assignment/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Entries</relationshipLabel>
        <relationshipName>Transaction_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Entry</label>
    <nameField>
        <displayFormat>TX-{00000}</displayFormat>
        <label>Transaction Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SRC/Major Assignment/classes/RecordPdfTest.cls
@isTest(seeAllData = false)
public class RecordPdfTest {
	@testSetup
    private static void gettingData(){
        List<Contact> newContact = new List<Contact>();
        Contact con = new Contact();
        con.LastName = 'Sagar';
        con.Status__c = 'Active';
        con.Email = 'sagarsafe@gamil.com';
        con.Available_Balance__c = 0;
        newContact.add(con);
        insert newContact;
        
        List<Transaction_Entry__c> entryList = new List<Transaction_Entry__c>();
        Transaction_Entry__c newEntry = new Transaction_Entry__c();
        newEntry.Amount__c = 20000;
        newEntry.Type__c = 'Debit';
        newEntry.Status__c = 'Pending';
        newEntry.Contact__c = newContact[0].id;
        newEntry.Transaction_Date__c = System.today();     
        entryList.add(newEntry);
        
        Transaction_Entry__c secondEntry = new Transaction_Entry__c();
        secondEntry.Amount__c = 20000;
        secondEntry.Type__c = 'Debit';
        secondEntry.Status__c = 'Pending';
        secondEntry.Contact__c = newContact[0].id;
        secondEntry.Transaction_Date__c = System.today();     
        entryList.add(secondEntry);
   	}
    
    @isTest
    private static void testingData(){
        List<Contact> conlist = [SELECT Id, Title, Name , Email, Account_Number__c FROM Contact WHERE LastName = 'Sagar'];
        System.assertEquals(1, conlist.size());
        Test.startTest();
        Records_PDF_Controller obj = new Records_PDF_Controller();
        obj.recordPdf();
        Test.stopTest();
    }
}